// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoSistemaEscolarAPI.Models.Context;

#nullable disable

namespace ProjetoSistemaEscolarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230215030347_CriacaoDoBancoDeDados")]
    partial class CriacaoDoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Alunos", b =>
                {
                    b.Property<Guid>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Escola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TurmasTurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlunoId");

                    b.HasIndex("Escola");

                    b.HasIndex("TurmasTurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Escolas", b =>
                {
                    b.Property<Guid>("EscolaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodigoUnidade")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdAlunos")
                        .HasColumnType("int");

                    b.Property<int>("QtdTurmas")
                        .HasColumnType("int");

                    b.HasKey("EscolaId");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Materias", b =>
                {
                    b.Property<Guid>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorDaMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdTurmasMatriculadas")
                        .HasColumnType("int");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.MateriasDasTurmas", b =>
                {
                    b.Property<Guid>("MateriaDaTurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Materia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Turma")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MateriaDaTurmaId");

                    b.HasIndex("Materia");

                    b.HasIndex("Turma");

                    b.ToTable("MateriasDasTurmas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turmas", b =>
                {
                    b.Property<Guid>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoDaTurma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Escola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QtdAlunos")
                        .HasColumnType("int");

                    b.HasKey("TurmaId");

                    b.HasIndex("Escola");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Alunos", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Escolas", "Escolas")
                        .WithMany("Alunos")
                        .HasForeignKey("Escola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Turmas", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmasTurmaId");

                    b.Navigation("Escolas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.MateriasDasTurmas", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Materias", "Materias")
                        .WithMany()
                        .HasForeignKey("Materia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Turmas", "Turmas")
                        .WithMany()
                        .HasForeignKey("Turma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materias");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turmas", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Escolas", "Escolas")
                        .WithMany("Turmas")
                        .HasForeignKey("Escola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escolas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Escolas", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turmas", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
