// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoSistemaEscolarAPI.Models.Context;

#nullable disable

namespace ProjetoSistemaEscolarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Aluno", b =>
                {
                    b.Property<Guid>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdTurma")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdTurma");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Instituicao", b =>
                {
                    b.Property<Guid>("IdInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodigoInstituicao")
                        .HasColumnType("int");

                    b.Property<int>("QtdAlunos")
                        .HasColumnType("int");

                    b.Property<int>("QtdCursos")
                        .HasColumnType("int");

                    b.Property<int>("QtdTurmas")
                        .HasColumnType("int");

                    b.HasKey("IdInstituicao");

                    b.ToTable("Instituicao");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Materia", b =>
                {
                    b.Property<Guid>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeMateria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorDaMateria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.MateriaXTurma", b =>
                {
                    b.Property<Guid>("IdMateriaTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMateria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTurma")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdMateriaTurma");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdTurma");

                    b.ToTable("MateriaXTurma");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turma", b =>
                {
                    b.Property<Guid>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoTurma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdInstituicao")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdTurma");

                    b.HasIndex("IdInstituicao");

                    b.ToTable("Turma");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Aluno", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.MateriaXTurma", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turma", b =>
                {
                    b.HasOne("ProjetoSistemaEscolarAPI.Models.Instituicao", "Instituicao")
                        .WithMany("Turmas")
                        .HasForeignKey("IdInstituicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Instituicao", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("ProjetoSistemaEscolarAPI.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
